export default {
    UPDATE_ALBUMS: 'UPDATE_ALBUMS',
    UPDATE_ALBUM: 'UPDATE_ALBUM',
    UPDATE_SONGS: 'UPDATE_SONGS',
    UPDATE_SONG: 'UPDATE_SONG',
    UPDATE_PLAYLISTS: 'UPDATE_PLAYLISTS',
    UPDATE_PLAYLIST: 'UPDATE_PLAYLIST',
    UPDATE_ARTISTS: 'UPDATE_ARTISTS',
    UPDATE_ARTIST: 'UPDATE_ARTIST',
    UPDATE_SEARCHED: 'UPDATE_SEARCHED',
}