export default [
  { path: '/', name:"dashboard", meta: {requireAuth: true}, children: [
    { path: 'explore', name:"explore", meta: {requireAuth: true}, component: () => import('../views/dashboard/exploreView.vue')},
    { path: 'recent', name:"recent", meta: {requireAuth: true}, component: () => import('../views/dashboard/recentView.vue')},
    { path: 'favorites', name:"favorites", meta: {requireAuth: true}, component: () => import('../views/dashboard/favoritesView.vue')},
    { path: 'albums', name:"albums", meta: {requireAuth: true}, component: () => import('../views/dashboard/albumsView.vue')},
    { path: 'albums/:album_id', name:"album", meta: {requireAuth: true}, component: () => import('../views/dashboard/albumView.vue')},
    { path: 'songs', name:"songs", meta: {requireAuth: true}, component: () => import('../views/dashboard/songsView.vue')},
    { path: 'songs/:song_id', name:"song", meta: {requireAuth: true}, component: () => import('../views/dashboard/songView.vue')},
    { path: 'artists', name:"artists", meta: {requireAuth: true}, component: () => import('../views/dashboard/artistsView.vue')},
    { path: 'artists/:artist_id', name:"artist", meta: {requireAuth: true}, component: () => import('../views/dashboard/artistView.vue')},
    { path: 'playlists', name:"playlists", meta: {requireAuth: true}, component: () => import('../views/dashboard/playlistsView.vue')},
    { path: 'playlists/:playlist_id', name:"playlist", meta: {requireAuth: true},  component: () => import('../views/dashboard/playlistView.vue')},
    { path: 'following', name:"following", meta: {requireAuth: true}, component: () => import('../views/dashboard/followingView.vue')},
    { path: 'settings', name:"settings", meta: {requireAuth: true}, component: () => import('../views/dashboard/settingsView.vue')},
    { path: 'account', name:"account", meta: {requireAuth: true}, component: () => import('../views/dashboard/accountView.vue')},
  ], component: () => import('../views/DashboardView.vue')},
  { path: '/login', name:"login", meta: {requireAuth: false}, component: () => import('../views/auth/LoginView.vue')},
  { path: '/artist-signup', name:"artistSignup",  meta: {requireAuth: false}, component: () => import('../views/auth/ArtistSignUpView.vue')},
  { path: '/signup', name:"userSignup", meta: {requireAuth: false}, component: () => import('../views/auth/UserSignUpView.vue')},
  { path: '/change-password', name:"changePassword", meta: {requireAuth: false}, component: () => import('../views/auth/ChangePasswordView.vue')},
  { path: '/reset-password', name:"resetPassword", meta: {requireAuth: false}, component: () => import('../views/auth/ResetPassword.vue')},
  { path: '/confirm-email', name:"confirmEmail", meta: {requireAuth: false}, component: () => import('../views/auth/ConfirmEmailView.vue')},
  { path: '/choose-account-type', name:"accountType", meta: {requireAuth: false}, component: () => import('../views/auth/ChooseAccountTypeView.vue')},
]